[package]
name = "ghostrelay-security"
version = "0.1.0"
edition = "2021"

[lib]
name = "ghostrelay_security"
crate-type = ["cdylib", "rlib"]

[dependencies]

#JNI Crate
jni = "0.21"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Randomness
rand = "0.8"
rand_core = "0.6"

# Memory wiping
zeroize = "1.8"

# UUIDs
uuid = { version = "1", features = ["v4", "serde"] }

# Time
chrono = { version = "0.4", features = ["serde"] }

# Base64
base64 = "0.22"

# Cryptography
x25519-dalek = { version = "2", features = ["static_secrets"] }
ed25519-dalek = { version = "2.2", features = ["rand_core"] }
chacha20poly1305 = "0.10"
sha2 = "0.10"

# Errors
thiserror = "2"